# docker-compose.yml

version: '3'

services:

    php:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: sakaidao2_php
        volumes:
            - .:/var/www
            - ./docker/php.ini:/usr/local/etc/php/conf.d/local.ini
        working_dir: /var/www
        depends_on:
            - mysql
        entrypoint: /var/www/start.sh

    nginx:
        image: nginx:latest
        container_name: sakaidao2_nginx
        ports:
            - "7071:80"
        volumes:
            - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./storage/logs:/var/log/nginx
            - .:/var/www
        depends_on:
            - php
            - mysql

    mysql:
        image: mysql:8.0
        container_name: sakaidao2_mysql
        environment:
            MYSQL_DATABASE: app
            MYSQL_ROOT_PASSWORD: K3DLMcq74aWwbF
            MYSQL_USER: admin
            MYSQL_PASSWORD: K3DLMcq74aWwbF
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - mysql_data:/var/lib/mysql
            - ./docker/my.cnf:/etc/mysql/my.cnf

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: sakaidao2_phpmyadmin
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306
        ports:
            - "7072:80"
        depends_on:
            - mysql

    web3js:
        build:
            context: ./web3js
            dockerfile: Dockerfile
        container_name: sakaidao2_web3
        volumes:
            - ./web3js:/usr/src/web3
        ports:
            - "7073:3001"

volumes:
    mysql_data:
